### ISSUE TITLE
VSCode里，执行该py文件后，下方 输出 窗口无法写入！

### ISSUE THREAD

**Issue by piwawa** [fiatrete/Chatbot-with-GPT3.5Turbo-API#1]
就是这样
![屏幕截图 2023-03-03 164731](https://user-images.githubusercontent.com/46926496/222674472-75f05e53-6b2f-4c8c-8171-4d5a6dc021a4.png)

**Comment by fiatrete** [comment]
run in a Terminal pls.

**Comment by piwawa** [comment]
> run in a Terminal pls.

请问这个chat log的对话格式在哪查的，怎么保证他能正确读取对话记录，然后联系上下文

**Comment by fiatrete** [comment]
I don't know what you mean, but I think you'd better check openai document.

**Comment by piwawa** [comment]
> I don't know what you mean, but I think you'd better check openai document.

Sorry, it's my bad that thought you are Chinese. 
I mean how to find the chat log format? I checked the official guide and didn't see it...

**Comment by fiatrete** [comment]
I don't think openai has any chat log format restriction. But if you are discussing chat context, you should know each conversation with ChatGPT is independent and unique as it responds based on the input it receives in real-time without retaining any memory of previous conversations(answer from ChatGPT). and according to this [document](https://platform.openai.com/docs/guides/chat/introduction), you can provide previous chat history while creating a chat by using the "messages" parameter.
